
import { PromptType } from "@/components/prompts/PromptCard";

// Mock de dados para categorias
export const categories = [
  { id: "criminal", name: "Direito Criminal" },
  { id: "civil", name: "Direito Civil" },
  { id: "family", name: "Direito de Família" },
  { id: "consumer", name: "Direito do Consumidor" },
  { id: "administrative", name: "Direito Administrativo" },
  { id: "environmental", name: "Direito Ambiental" },
];

// Mock de dados para prompts
export const mockPrompts: PromptType[] = [
  {
    id: "1",
    title: "Manifestação de Arquivamento de Inquérito Policial",
    description: "Modelo para arquivamento de IP com fulcro no art. 395, III, do CPP, quando não houver justa causa para o exercício da ação penal.",
    content: "MM. Juiz,\n\nTrata-se de Inquérito Policial instaurado para apurar a prática, em tese, do crime previsto no art. X da Lei Y, tendo como indiciado Fulano de Tal...",
    category: "criminal",
    keywords: ["arquivamento", "inquérito", "justa causa"],
    isPublic: true,
    createdBy: {
      id: "user1",
      name: "João Silva",
      role: "Promotor de Justiça",
      avatar: "",
    },
    createdAt: "2023-10-15T10:30:00Z",
    updatedAt: "2023-10-15T10:30:00Z",
    likesCount: 42,
    isLiked: false,
    isFavorited: false,
  },
  {
    id: "2",
    title: "Alegações Finais em Processo de Tráfico de Drogas",
    description: "Modelo de alegações finais em processo criminal de tráfico de drogas com pedido de condenação.",
    content: "MM. Juiz,\n\nO Ministério Público, por seu representante legal, nos autos do processo em epígrafe, vem apresentar ALEGAÇÕES FINAIS, nos seguintes termos...",
    category: "criminal",
    keywords: ["alegações finais", "tráfico", "drogas", "condenação"],
    isPublic: true,
    createdBy: {
      id: "user2",
      name: "Maria Oliveira",
      role: "Promotora de Justiça",
      avatar: "",
    },
    createdAt: "2023-10-10T14:20:00Z",
    updatedAt: "2023-10-11T09:15:00Z",
    likesCount: 35,
    isLiked: true,
    isFavorited: false,
  },
  {
    id: "3",
    title: "Recomendação para Adequação Ambiental",
    description: "Modelo de recomendação para que empresa se adeque às normas ambientais após constatação de irregularidades.",
    content: "RECOMENDAÇÃO Nº XX/20XX\n\nO MINISTÉRIO PÚBLICO DO ESTADO X, por meio da Promotoria de Justiça de Defesa do Meio Ambiente...",
    category: "environmental",
    keywords: ["recomendação", "meio ambiente", "adequação"],
    isPublic: true,
    createdBy: {
      id: "user3",
      name: "Carlos Mendes",
      role: "Promotor de Justiça",
      avatar: "",
    },
    createdAt: "2023-09-28T16:45:00Z",
    updatedAt: "2023-09-30T11:20:00Z",
    likesCount: 27,
    isLiked: false,
    isFavorited: true,
  },
  {
    id: "4",
    title: "Ação Civil Pública - Improbidade Administrativa",
    description: "Modelo de ACP por ato de improbidade administrativa contra agente público que causou prejuízo ao erário.",
    content: "EXCELENTÍSSIMO(A) SENHOR(A) DOUTOR(A) JUIZ(A) DE DIREITO DA VARA DA FAZENDA PÚBLICA DA COMARCA DE X...",
    category: "administrative",
    keywords: ["improbidade", "ação civil pública", "erário"],
    isPublic: true,
    createdBy: {
      id: "user4",
      name: "Ana Sousa",
      role: "Promotora de Justiça",
      avatar: "",
    },
    createdAt: "2023-10-05T09:30:00Z",
    updatedAt: "2023-10-05T09:30:00Z",
    likesCount: 18,
    isLiked: false,
    isFavorited: false,
  },
  {
    id: "5",
    title: "Parecer em Ação de Alimentos",
    description: "Modelo de parecer favorável em ação de alimentos movida em favor de menor.",
    content: "MM. Juiz,\n\nTrata-se de ação de alimentos proposta por X, menor impúbere, representado por sua genitora, em face de Y, seu genitor...",
    category: "family",
    keywords: ["alimentos", "parecer", "família"],
    isPublic: true,
    createdBy: {
      id: "user5",
      name: "Paulo Ferreira",
      role: "Promotor de Justiça",
      avatar: "",
    },
    createdAt: "2023-10-08T13:15:00Z",
    updatedAt: "2023-10-09T10:00:00Z",
    likesCount: 23,
    isLiked: false,
    isFavorited: false,
  },
  {
    id: "6",
    title: "Denúncia - Crime Contra o Consumidor",
    description: "Modelo de denúncia para crimes contra as relações de consumo, com base no CDC.",
    content: "EXCELENTÍSSIMO SENHOR DOUTOR JUIZ DE DIREITO DA VARA CRIMINAL DA COMARCA DE X...",
    category: "consumer",
    keywords: ["denúncia", "consumidor", "CDC"],
    isPublic: true,
    createdBy: {
      id: "user2",
      name: "Maria Oliveira",
      role: "Promotora de Justiça",
      avatar: "",
    },
    createdAt: "2023-10-12T11:00:00Z",
    updatedAt: "2023-10-12T11:00:00Z",
    likesCount: 15,
    isLiked: false,
    isFavorited: false,
  },
];

// Mock do usuário atual - seria substituído pelos dados do Azure AD
export const currentUser = {
  id: "user1",
  name: "Usuário MP",
  role: "Promotor de Justiça",
  unit: "Central de Inquéritos",
  email: "usuario@mp.gov.br",
  avatar: "",
  interests: ["Direito Criminal", "Direito Ambiental"],
  location: "São Paulo, SP",
};
